# -*- coding: utf-8 -*-
"""PRO-C123-Project-Boilerplate-Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Zip3tsLXc3RL7L0cifwJlAeOJn0cu01

**Archery-Target** is a game in which the players shoot sharp-pointed arrows at a round target having 10 rings.

<img src="https://s3-whjr-curriculum-uploads.whjr.online/4de9132a-c71d-42ce-9099-3293e8805fd9.jpg">

## RL Problem to Solve
Hit the center of the target with maximum reward

<img src="https://s3-whjr-curriculum-uploads.whjr.online/40656a8c-14e2-4dd7-9f9e-4c17669b9182.png" width=300>


Number of **State**: ?

Number of **Actions**: ?

## Rewards
"""

#import required libraries
import numpy as np
import random



"""## Reward Matrix
Reward Matrix represents states as rows and actions as columns with respective awards values assigned for a given state and action pair.
"""

#Create reward matrix
rewards = np.array([10,9,8,7,6,5,4,3,2,1])
"""## Take Action Randomly"""

#Define a function shoot() for taking random action
def shoot():
    return(np.random.randint(0,10))
output = shoot()
print(shoot) 